require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommitteeMemberEvaluatsController do

  # This should return the minimal set of attributes required to create a valid
  # CommitteeMemberEvaluat. As you add validations to CommitteeMemberEvaluat, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommitteeMemberEvaluatsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all committee_member_evaluats as @committee_member_evaluats" do
      committee_member_evaluat = CommitteeMemberEvaluat.create! valid_attributes
      get :index, {}, valid_session
      assigns(:committee_member_evaluats).should eq([committee_member_evaluat])
    end
  end

  describe "GET show" do
    it "assigns the requested committee_member_evaluat as @committee_member_evaluat" do
      committee_member_evaluat = CommitteeMemberEvaluat.create! valid_attributes
      get :show, {:id => committee_member_evaluat.to_param}, valid_session
      assigns(:committee_member_evaluat).should eq(committee_member_evaluat)
    end
  end

  describe "GET new" do
    it "assigns a new committee_member_evaluat as @committee_member_evaluat" do
      get :new, {}, valid_session
      assigns(:committee_member_evaluat).should be_a_new(CommitteeMemberEvaluat)
    end
  end

  describe "GET edit" do
    it "assigns the requested committee_member_evaluat as @committee_member_evaluat" do
      committee_member_evaluat = CommitteeMemberEvaluat.create! valid_attributes
      get :edit, {:id => committee_member_evaluat.to_param}, valid_session
      assigns(:committee_member_evaluat).should eq(committee_member_evaluat)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommitteeMemberEvaluat" do
        expect {
          post :create, {:committee_member_evaluat => valid_attributes}, valid_session
        }.to change(CommitteeMemberEvaluat, :count).by(1)
      end

      it "assigns a newly created committee_member_evaluat as @committee_member_evaluat" do
        post :create, {:committee_member_evaluat => valid_attributes}, valid_session
        assigns(:committee_member_evaluat).should be_a(CommitteeMemberEvaluat)
        assigns(:committee_member_evaluat).should be_persisted
      end

      it "redirects to the created committee_member_evaluat" do
        post :create, {:committee_member_evaluat => valid_attributes}, valid_session
        response.should redirect_to(CommitteeMemberEvaluat.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved committee_member_evaluat as @committee_member_evaluat" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommitteeMemberEvaluat.any_instance.stub(:save).and_return(false)
        post :create, {:committee_member_evaluat => {}}, valid_session
        assigns(:committee_member_evaluat).should be_a_new(CommitteeMemberEvaluat)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommitteeMemberEvaluat.any_instance.stub(:save).and_return(false)
        post :create, {:committee_member_evaluat => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested committee_member_evaluat" do
        committee_member_evaluat = CommitteeMemberEvaluat.create! valid_attributes
        # Assuming there are no other committee_member_evaluats in the database, this
        # specifies that the CommitteeMemberEvaluat created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommitteeMemberEvaluat.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => committee_member_evaluat.to_param, :committee_member_evaluat => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested committee_member_evaluat as @committee_member_evaluat" do
        committee_member_evaluat = CommitteeMemberEvaluat.create! valid_attributes
        put :update, {:id => committee_member_evaluat.to_param, :committee_member_evaluat => valid_attributes}, valid_session
        assigns(:committee_member_evaluat).should eq(committee_member_evaluat)
      end

      it "redirects to the committee_member_evaluat" do
        committee_member_evaluat = CommitteeMemberEvaluat.create! valid_attributes
        put :update, {:id => committee_member_evaluat.to_param, :committee_member_evaluat => valid_attributes}, valid_session
        response.should redirect_to(committee_member_evaluat)
      end
    end

    describe "with invalid params" do
      it "assigns the committee_member_evaluat as @committee_member_evaluat" do
        committee_member_evaluat = CommitteeMemberEvaluat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommitteeMemberEvaluat.any_instance.stub(:save).and_return(false)
        put :update, {:id => committee_member_evaluat.to_param, :committee_member_evaluat => {}}, valid_session
        assigns(:committee_member_evaluat).should eq(committee_member_evaluat)
      end

      it "re-renders the 'edit' template" do
        committee_member_evaluat = CommitteeMemberEvaluat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommitteeMemberEvaluat.any_instance.stub(:save).and_return(false)
        put :update, {:id => committee_member_evaluat.to_param, :committee_member_evaluat => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested committee_member_evaluat" do
      committee_member_evaluat = CommitteeMemberEvaluat.create! valid_attributes
      expect {
        delete :destroy, {:id => committee_member_evaluat.to_param}, valid_session
      }.to change(CommitteeMemberEvaluat, :count).by(-1)
    end

    it "redirects to the committee_member_evaluats list" do
      committee_member_evaluat = CommitteeMemberEvaluat.create! valid_attributes
      delete :destroy, {:id => committee_member_evaluat.to_param}, valid_session
      response.should redirect_to(committee_member_evaluats_url)
    end
  end

end
